In [1]:
data_path="/Users/ramj/tvr-works/gh/venkataramant/uta-pg-aiml/material/python/week2"

In [2]:
data_path

'/Users/ramj/tvr-works/gh/venkataramant/uta-pg-aiml/material/python/week2'

In [7]:
data_file="books.csv"

In [4]:
import pandas as pd

In [8]:
df=pd.read_csv(f"{data_path}/{data_file}")

In [9]:
df

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427,en-US,534.0,140,22,Modern Library,2004
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
2,Breach of Promise,James Scott Bell,4.00,9780310243878,eng,345.0,368,36,Zondervan,2004
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889,eng,273.0,18335,1155,Abacus,2000
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006
...,...,...,...,...,...,...,...,...,...,...
4995,The Complete Works,Michel de Montaigne,4.44,9781400040216,eng,1392.0,166,13,Everyman's Library,2003
4996,Shipwreck (Island I),Gordon Korman,3.80,9780439023313,eng,NaN,103,14,Scholastic Audio Books,2007
4997,Every Night Italian: Every Night Italian,Giuliano Hazan,3.79,9780684800288,eng,256.0,70,2,Scribner,2000
4998,Go Down Moses,William Faulkner,3.93,9780679732174,eng,365.0,8289,370,Vintage,1991
4999,The Avignon Quintet: Monsieur Livia Constanc...,Lawrence Durrell,4.07,9780571225552,en-US,1376.0,287,23,Faber & Faber,2004

In [10]:
import numpy as np

In [12]:
df.shape

(5000, 10)

In [13]:
df.describe()

,average_rating,isbn13,num_pages,ratings_count,text_reviews_count,year
count,5000.000000,5.000000e+03,4967.000000,5.000000e+03,5000.000000,5000.000000
mean,3.931932,9.752758e+12,341.094021,2.017549e+04,592.688600,2000.131800
std,0.348741,5.129254e+11,230.986115,1.175026e+05,2539.539004,8.069043
min,0.000000,8.987060e+09,1.000000,0.000000e+00,0.000000,1913.000000
25%,3.770000,9.780345e+12,200.000000,1.050000e+02,9.000000,1998.000000
50%,3.960000,9.780571e+12,304.000000,7.915000e+02,49.000000,2003.000000
75%,4.140000,9.780871e+12,416.500000,5.348750e+03,249.000000,2005.000000
max,5.000000,9.789879e+12,3342.000000,2.457092e+06,55843.000000,2019.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               5000 non-null   object
 1   author              5000 non-null   object
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   int64
 4   language_code       4923 non-null   object
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64
 7   text_reviews_count  5000 non-null   int64
 8   publisher           5000 non-null   object
 9   year                5000 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 390.8+ KB

In [28]:
df[df.average_rating>4]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006
5,The Hand of Chaos (The Death Gate Cycle #5),Margaret Weis,4.06,9780553563696,eng,446.0,16301,117,Spectra,1993
6,On Intelligence,Jeff Hawkins,4.12,9780805078534,eng,261.0,5347,396,St. Martin's Griffin,2005
11,Merlin's Tour of the Universe,Neil deGrasse Tyson,4.02,9780385488358,eng,318.0,305,27,Main Street Books,1997
...,...,...,...,...,...,...,...,...,...,...
4991,'Salem's Lot,Stephen King,4.02,9780965772419,eng,405.0,1039,130,Doubleday,1975
4992,A Mad People's History of Madness,Dale Peterson,4.33,9780822953319,eng,384.0,9,0,University of Pittsburgh Press,1982
4993,A Christmas Carol (Great Illustrated Classics),Malvina G. Vogel,4.36,9781596792371,eng,238.0,466,31,Abdo Publishing Company,2005
4995,The Complete Works,Michel de Montaigne,4.44,9781400040216,eng,1392.0,166,13,Everyman's Library,2003
4999,The Avignon Quintet: Monsieur Livia Constanc...,Lawrence Durrell,4.07,9780571225552,en-US,1376.0,287,23,Faber & Faber,2004

In [16]:
df.head()

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427,en-US,534.0,140,22,Modern Library,2004
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
2,Breach of Promise,James Scott Bell,4.00,9780310243878,eng,345.0,368,36,Zondervan,2004
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889,eng,273.0,18335,1155,Abacus,2000
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006

In [39]:
df[(df.average_rating>4.5) & (df.ratings_count<10)].size

250

In [37]:
df[(df['average_rating']>4.5) & (df['ratings_count']<10)].size

250

In [42]:
df[df['language_code']=='eng'].describe()

,average_rating,isbn13,num_pages,ratings_count,text_reviews_count,year
count,3990.000000,3.990000e+03,3965.000000,3.990000e+03,3990.000000,3990.000000
mean,3.931143,9.754850e+12,341.497604,2.432663e+04,705.539348,1999.994236
std,0.357624,4.918212e+11,235.847754,1.310014e+05,2821.106044,7.998227
min,0.000000,2.375500e+10,1.000000,0.000000e+00,0.000000,1913.000000
25%,3.770000,9.780345e+12,200.000000,1.422500e+02,11.000000,1998.000000
50%,3.960000,9.780553e+12,304.000000,1.082000e+03,62.000000,2002.000000
75%,4.140000,9.780813e+12,416.000000,6.892500e+03,303.750000,2005.000000
max,5.000000,9.789792e+12,3342.000000,2.457092e+06,55843.000000,2019.000000

In [43]:
df[df['language_code']=='eng']['average_rating'].mean()

3.931142857142857

In [44]:
df.columns

Index(['title', 'author', 'average_rating', 'isbn13', 'language_code',
       'num_pages', 'ratings_count', 'text_reviews_count', 'publisher',
       'year'],
      dtype='object')

In [51]:
df.iloc[0:5,:]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427,en-US,534.0,140,22,Modern Library,2004
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
2,Breach of Promise,James Scott Bell,4.00,9780310243878,eng,345.0,368,36,Zondervan,2004
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889,eng,273.0,18335,1155,Abacus,2000
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006

In [50]:
df.loc[[1,4],['language_code', 'num_pages', 'ratings_count']]

  language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524

In [52]:
df.describe()

,average_rating,isbn13,num_pages,ratings_count,text_reviews_count,year
count,5000.000000,5.000000e+03,4967.000000,5.000000e+03,5000.000000,5000.000000
mean,3.931932,9.752758e+12,341.094021,2.017549e+04,592.688600,2000.131800
std,0.348741,5.129254e+11,230.986115,1.175026e+05,2539.539004,8.069043
min,0.000000,8.987060e+09,1.000000,0.000000e+00,0.000000,1913.000000
25%,3.770000,9.780345e+12,200.000000,1.050000e+02,9.000000,1998.000000
50%,3.960000,9.780571e+12,304.000000,7.915000e+02,49.000000,2003.000000
75%,4.140000,9.780871e+12,416.500000,5.348750e+03,249.000000,2005.000000
max,5.000000,9.789879e+12,3342.000000,2.457092e+06,55843.000000,2019.000000

In [57]:
df[df.year==2010].shape

(15, 10)

In [58]:
len(df[df.year==2010])

15

In [59]:
df[(df.average_rating>4)&(df.publisher=="DAW")]

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
71,By the Sword (Valdemar),Mercedes Lackey,4.25,9780886774639,eng,492.0,18531,249,DAW,1991
871,Storm Rising (Valdemar: Mage Storms #2),Mercedes Lackey,4.02,9780886777128,en-US,412.0,10781,86,DAW,1996
1523,Phoenix and Ashes (Elemental Masters #3),Mercedes Lackey,4.01,9780756402723,eng,480.0,6980,229,DAW,2005
1583,To Battle the Gods (Jalav Amazon Warrior #5),Sharon Green,4.07,9780886771287,eng,446.0,87,1,DAW,1986
3726,Oathblood (Valdemar: Vows and Honor #3),Mercedes Lackey,4.06,9780886777739,en-GB,394.0,9786,103,DAW,1998
4367,Joust (Dragon Jousters #1),Mercedes Lackey,4.02,9780756401535,eng,448.0,10113,263,DAW,2004

In [62]:
df[(df.num_pages>500)&(df.year>2010)].shape

(5, 10)

In [63]:
df[df.author=="Agatha Christie"].shape

(21, 10)

In [65]:
df[(df.language_code=="spa")&(df.year>2000)].count()

title                 84
author                84
average_rating        84
isbn13                84
language_code         84
num_pages             83
ratings_count         84
text_reviews_count    84
publisher             84
year                  84
dtype: int64